image: "python:3.10"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

pylint:
    stage: build
    script:
    - echo "Building the code..."
    - pylint -d C0301 src/main.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Boundary/FormTDL.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Boundary/TDLDisplay.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Controller/TDLController.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Entity/ToDoList.py
    - echo "Building complete."

pytest:
    stage: test
    script:
    - echo "Testing the code..."
    - echo "Testing complete."
