image: "python:3.10"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

pylint:
    stage: build
    script:
    - echo "Building the code..."
    - pylint -d C0301 src/main.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Boundary/FormTDL.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Boundary/TDLDisplay.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Controller/TDLController.py
    - pylint -d C0301 src/CatatanHandler/ToDoList/Entity/ToDoList.py
    - pylint -d C0301 src/CatatanHandler/CatatanHarian/Boundary/FormHarian.py
    - pylint -d C0301 src/CatatanHandler/CatatanHarian/Boundary/HarianDisplay.py
    - pylint -d C0301 src/CatatanHandler/CatatanHarian/Controller/HarianController.py
    - pylint -d C0301 src/CatatanHandler/CatatanHarian/Entity/CatatanHarian.py
    - pylint -d C0301 src/CatatanHandler/Calendar/Calendar.py
    - pylint -d C0301 src/CatatanHandler/Calendar/CalendarToDo.py
    - pylint -d C0301 src/CatatanHandler/ConfirmPopUp/ConfirmPopUp.py
    - pylint -d C0301 src/CatatanHandler/CatatanTarget/Boundary/FormTarget.py
    - pylint -d C0301 src/CatatanHandler/CatatanTarget/Boundary/TargetDisplay.py
    - pylint -d C0301 src/CatatanHandler/CatatanTarget/Entity/CatatanTarget.py
    - pylint -d C0301 src/CatatanHandler/CatatanTarget/Controller/TargetController.py
    - pylint -d C0301 src/CatatanHandler/CatatanSyukur/Boundary/FormSyukur.py
    - pylint -d C0301 src/CatatanHandler/CatatanSyukur/Boundary/SyukurDisplay.py
    - pylint -d C0301 src/CatatanHandler/CatatanSyukur/Entity/CatatanSyukur.py
    - pylint -d C0301 src/CatatanHandler/CatatanSyukur/Controller/SyukurController.py

    - echo "Building complete."

pytest:
    stage: test
    script:
    - echo "Testing the code..."
    - echo "Testing complete."
